2023-02-25 16:45:32.330707
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Elsiros\controllers\SAMPLE_TEAM\main_pb.py", line 117, in main_procedure
    robot = CommunicationManager(1, '127.0.0.1', int(Port), logarg, team_color=sys.argv[3].upper(), player_number = int(sys.argv[4]), time_step = 25)
  File "C:\Elsiros\controllers\player\communication_manager_robokit.py", line 14, in __init__
    self.__client.connect_client()
  File "C:\Elsiros\controllers\player\robot_client.py", line 69, in connect_client
    welcome_message = self.socket.recv(8)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
